### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by unabomber78** [ElvisBlue/x64dbgpython#1]
windows 10x64
Python 3.10.6-64 installed in custom path C:\Python310 but it added to path enviroment.
Python 3.10.6-32 installed in default path and also added to path enviroment.
x64dbg sep 2 2022 
x64dbg log
Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing Zydis...
Getting directory information...
Start file read thread...
Retrieving syscall indices...
Symbol Path: C:\x64dbg\release\x64\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
[PLUGIN] Failed to load plugin: x64dbgpython.dp64
Handling command line...
  "C:\x64dbg\release\x64\x64dbg.exe" 
Syscall indices loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!

**Comment by ElvisBlue** [comment]
I have just add build version for python 3.10. Please check and report.

**Comment by unabomber78** [comment]
Upgraded python solved the problem.
